config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root "home#top"
 
  get 'posts/create'
  # post "/posts/:id/edit" => "posts#edit"
  # ホーム画面で業務を一覧表示させるため、indexアクションとする
  get  "/home" => "posts#index" 
  
  
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  
  
  resources :users
  resources :posts
  #投稿（業務提出)に関するルーティングを設定する
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
  # scope:任意の名前,->(引数（任意の名前)　{ where(カラム名: "カラム内の値).where(cd: value) }
  scope :status, ->(value) { where(cd_type: "status").where(cd: value).first }
  
  #updeteで進捗の変更に使うためのもの
  scope :status_select,-> {where(cd_type:"status")}
  scope :priority_select, -> {where(cd_type:"priority")}
  # gem 'hirb'  gem 'hirb-unicode'の２つをインストールすることで、:status_selectをCode.status_selectとしてデータを取得できる。  
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true,length:{maximum:50}
  validates :description, presence: true
  validates :appointed_user_id,presence: true
  validates :due_date, presence: true
  
  belongs_to :user
  # appointed_user_idとappointed_userの関連付け
  belongs_to :appointed_user, class_name: "User"
end
 

app/models/user.rb
class User < ApplicationRecord
  validates:name, presence: true,length:{maximum:20}
  validates:email,presence: true,uniqueness: true,format:{with:/\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i}
  validates :password, presence: true, length: { minimum: 8, maximum: 32}, format: { with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])\w{8,32}\z/}
  
  has_secure_password
  has_many :posts
  
  def post_change
    self.experience -= 1
    self.save(validate: false)
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger, :primary
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    #変数@current_userの値がnilまたはfalseであれば、User以下を代入するし、それ以外の場合は@current_userの値をそのまま使用するという意味になる。
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    #以下のコードは、当初Post.where(status:"1",appointed_user_id: current_user.id).countとしていた。これでは、担当者の各ステータスが取得できないでので、appointed_user_idに修正
    @complete = Post.where(status:"1",appointed_user_id: current_user.id).count 
    @in_progress = Post.where(status:"2",appointed_user_id: current_user.id).count
    @not_yet = Post.where(status:"3",appointed_user_id: current_user.id).count
    # 以下の書き方もある
    # @complete = Post.where(status:"1").where(appointed_user_id: current_user.id).count 
    
    
    # 以下は、円グラフの凡例を導入するためのコード
    sum = @complete + @in_progress + @not_yet
    if sum == 0
       @complete_per = sprintf("%.1f",0)
       @in_progress_per = sprintf("%.1f",0)
       @not_yet_per = sprintf("%.1f",0)
    else 
       @complete_per = sprintf("%.1f",@complete/sum.to_f * 100)
       @in_progress_per = sprintf("%.1f",@in_progress/sum.to_f * 100)
       @not_yet_per = sprintf("%.1f",@not_yet/sum.to_f * 100)
    end
    
    @posts = Post.where(appointed_user_id: current_user.id)
    #上記コードは、当初where(user_id: current_user.id)としていた。しかし、これだとuser_idの値つまり、ログイン中のユーザーhomeに業務が追加されてしまうので、修正した。
    #追加した業務をユーザ別に一覧で表示するためのコード。Post.allとすると、全てのユーザーの　post内容が表示されてしまう。
  end
  
  
  def new
    @post = Post.new
  end
  
  #投稿の追加ボタンが押された時のデータ受け渡しの処理
  def create
    @post = current_user.posts.new(post_params)
    # 上記の書き方は、省略した書き方となる。基本に従って書くと以下の様になる
    # @post = Post.new
    # @post.user_id = current_user.id
    # @post.title = post_params[:title]
    # @post.description = post_params[:description]
    # @post.work_hour = post_params[:work_hour]
    # @post.due_date = post_params[:due_date]
    # @post.URL = post_params[:URL]
    # @post.appointed_user_id = post_params[:appointed_user_id]
    
     if @post.save 
       redirect_to home_path, success:"業務を追加しました。"
     else
       flash.now[:danger] = "業務を追加できませんでした。必須項目は必ず記入してください。"
       render :new 
     end
  end
  
  
  def edit
    #以下のように投稿を特定するためののコードを記載する。登録者の名前は直接edit.html.erbに直接記載している。
    #sessionとparamsはハッシュの中でもparams[:id],session[:user_id]のように特殊な書き方をする.
    @post = Post.find(params[:id])
  end
  
  
  def update
    @post = Post.find(params[:id])
    user = current_user
    # user = @post.user 当初は左の様に書いていたが、これでは投稿したユーザーの情報を更新してしまうため、current_userに変更した。
    
    
    # models/user.rbでユーザーに関するメソッドを定義していたが、ユーザーのレベルが上がった時のみにflashを個別で設定するために、レベルupに関するコードはここに記述することとする。
    if @post.status != "1" 
      if @post.update(post_params)
        if @post.status == "1"
           if user.experience += 1
             if user.experience == user.user_level
               user.user_level += 1
               user.experience = 0
               flash[:primary] = "✨ Level Up! Well done! ✨"
             end
           end
        end
        user.save(validate: false)
        redirect_to posts_path,success: "業務を更新しました。"
      else
        render :edit
      end
      
    elsif @post.status == "1" 
      @post.update(post_params)
      if @post.status != "1"
        user.post_change
        redirect_to posts_path,success: "業務を更新しました。"
      else 
        redirect_to posts_path,success: "業務を更新しました。"
      end
    else
      render :edit
    end
    
  end
  
  
  private 
  def post_params
    #requireのあとにはオブジェクト名シンボルとしてが来る。つまり、postテーブル。permitで取得できるカラム（キー)が指定されて、テーブル内の値がvalueとして取得できる。
    #permitのところで:statusを記載していなかったため、Code.status_selectをターミナルで実行してもstatusの値が取得できていなかった。
    params.require(:post).permit(:title,:description,:work_hour,:due_date,:priority,:URL,:appointed_user_id,:status,:experience,:user_level)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController #ログイン用のコントローラはsessionsを用いいるため、Sessionsコントローラとした
  def new
  end
  
  def create
    user = User.find_by(email: params[:sessions][:email])
    if user && user.authenticate(params[:sessions][:password])
      log_in user
      redirect_to home_path,success: "ログインに成功しました"
     
    else
      flash.now[:danger] = "メールアドレスもしくはパスワードが間違っています"
      render :new
    end
  end
  
  
  
  def destroy
    log_out
    redirect_to root_path, info: "ログアウトしました"
  end
  
  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  
  def create
     @user = User.new(user_params)
     @user.role = 0
    if @user.save
      redirect_to login_path, success:"登録が完了しました"
    else
      flash.now[:danger] = "登録に失敗しました 　※パスワードは8〜32字。大小字を含むアルファベット、数字をそれぞれ１文字以上組み合わせて下さい。"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class = "top-hero-wrapper text-center">
  <div class = "container top-hero-container">
      <h1 class ="concept-text ENG">Enrich your life.</h1>
      <h2 class = "concept-text">~人生を豊かにしよう~</h2>
      <h3 class = "concept-text">Freedomはテレワークを通じて、人生を豊かにするためのアプリケーションです。</h3>
      <div class = "row">
        <div class = "col-md-offset-3 col-md-3">
          <%= link_to 'Sign in', '/users/new', class: 'btn btn-block btn-white' %>
        </div>
        <div class = "col-md-3">
          <%= link_to 'Log in', login_path ,class: 'btn btn-block btn-white' %>
        </div>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freedom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js" type="text/javascript"></script>

  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container padding-l0">
        <% if logged_in? %>
          <%= link_to home_path do %> 
            <span><%= image_tag "freedom.logo.png" ,class:"freedom_logo"%></span>
          <% end %>
        <% else %>
           <span><%= image_tag "freedom.logo.png",class:"freedom_logo" %></span>
        <% end %>
        
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="nav-info">
              ログイン中のユーザー: <%= @current_user.name %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "logout.png" ,class:"logout"%>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(10000);
      });
      
      
    </script>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="home-wrapper-for-add">
  <div class="container">
    <div class="row edit-margin-lr0">
      <div class="background row">
        <h4 class="col-md-12 added_user_name">
          業務登録者：<%= @post.user.name %>
        </h4>
      </div>
        
      <%= form_for @post ,url:{controller:"posts",action:"update",id: @post.id} do |f| %>
        <div class="row">
          <div class="col-md-12 form-group">
            <%= f.label :description,"◆タイトル ：" %>
            <%= @post.title %>
          </div>
        </div>     
        <div class="row">
          <div class="col-md-12 form-group">
            <%= f.label :description,"◆業務詳細" %>
            <%= f.text_area :description, size:"20vw x 10vh",class:"form-control"%>
          </div>
        </div>
        <div class="row">
          <p class="col-md-2 form-group">
            <%= f.label :work_hour,"◆作業想定時間" %> : <%= @post.work_hour %> <%= f.label :work_hour,"時間" %>
          </p>
          <p class="col-md-2 form-group">
            <%= f.label :priority,"◆優先度" %> : <%= Code.find(@post.priority).name %>
            <!--優先度は上記の内容で取り出す事ができた。Codeテーブル.find(@post.priority ※ポストテーブルの中のpriorityカラムの値という意味).name ※Codeテーブルのnameカラムの値-->
          </p>
          </div>
          <div class="row">
            <div class="col-md-12 form-group">
              <%= f.label :URL,"◆成果物URL(データファイルのURLを添付してください)"%>
              <%= f.url_field :URL,class:"form-control"%>
            </div>
          </div>
          <div class="row">
            <div class="col-md-5 form-group">
              <%= f.label :status,"◆進捗状況" %>
              <%= f.collection_select :status,Code.status_select,:id,:name,{size:"15vw x 5vh"},{class:"form-control"} %>
            </div>
          </div>
          <div class="row btn-for-edit-add">
            <div class="col-md-offset-10 col-md-2 add-btn-location">
              <%= f.submit "作業報告をする",class:"btn btn-block btn-add-work" %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
 <div class="home-wrapper">
  <div class="container">
    <!--<div class="row"> ズレるのはmargin-left,right が原因-->
      <div class="row col-md-8 user_information">
        <ul class="user_status">
    　     <% if logged_in? %>
            <li class="col-md-7 current_user_name">
             ユーザー名: <%= @current_user.name %>
            </li>
            <li class="col-md-5 user_level">
         　   ユーザーLv. <%= @current_user.user_level %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="col-md-4 add_work_btn">
        <%= link_to "業務を追加",new_post_path,class:'btn btn-block btn-add' %>
      </div>
      <div class="row">
        <div class="col-md-7 work_index">
          <p class="work_title">◆業務一覧</p>
          <div class="work_index_space">
            <div class="work_index_title">
              <ul class="row">
                <li class="col-md-6 work_info text_1">タイトル</li>
                <li class ="col-md-2 work_info">進捗状況</li>
                <li class="col-md-4 work_info due_date_title">提出期限</li> 
              </ul>
              <div class="work_index_body">
                <% @posts.each do |post| %>
                  <ul class="gyoumu row"> 
                    <li class="col-md-6 each_work"> <%= link_to truncate(post.title,length:20),edit_post_path(post.id),class:'btn btn-block btn-work_desc' %> </li>
                    <li class="col-md-2 work_status_name"><%= Code.status(post.status).name %></li>
                    <li class="col-md-4 work_due_date"><%= post.due_date.strftime("%Y年%m月%d日%-H時%-M分") %></li>
                  </ul>  
                <% end %>
              </div>
            </div>
          </div>
        </div>
       
        <div class="col-md-5 work_chart">
          <p class="work_title2">◆業務状況</p>
          <div class="pie_chart">
            <!--ここに円グラフを入れ込みたいので、canvasを記述する-->
            <!--以下はjsのコードを参照するためにメンターに教えて頂いた内容。①inputタグを作成する。-->
            <!--この時、type="hidden",idは任意のものを作成、valueはposts#indexで変数にしたいものとする-->
            <!--value で定義した@○○をposts#indexでも定義して、任意の数値を代入する-->
            <input type="hidden" id="complete" value=<%= @complete %>> <!--完了の数値-->
            <input type="hidden" id="in_progress" value=<%= @in_progress %>> <!--対応中の数値-->
            <input type="hidden" id="not_yet" value=<%= @not_yet %>> <!--未対応の数値-->
            <canvas id="graph-area" height="300px" width="300px"></canvas>
            <!--ここまでが円グラフの数値とグラフの大きさに関するコード-->
            
          </div>
          <div class="work_status_info">
            <ul　class="work_status_info_item">
              <!--円グラフの凡例としてリストを使用したいため、idを追記（posts#indexで定義するものと同じ名前にする）。posts#indexで定義した内容を表示するために＜％＞で括る-->
              <li class="situation cp" id="complete_per" >　完了：<%=@complete_per%> ％</li>
              <li class= "situation ip" id="in_progress_per">対応中：<%=@in_progress_per%>  %</li>
              <li class= "situation nyp" id="not_yet_per">未対応：<%=@not_yet_per%>  %</li>
            </ul>
          </div>
        </div>
      </div>
  </div>
 </div>



<!--<script></script>は基本的にはどこに記載しても問題はないので、最後か別のファイルにコードを記載する。そうすることで、可読性が上がるとともに、ロード時間が短くなる -->
<script type="text/javascript">
  //以下は、inputタグの値を取得するためのjsのコード
  var complete=document.getElementById("complete").value;
  var in_progress=document.getElementById("in_progress").value;
  var not_yet=document.getElementById("not_yet").value;
  //ここまでがinputタグを参照するためのコード

  var pieData = [
    {
     value: complete,            // 値　※input_hiddenタグのvalueに合わせる
     color:"palegreen",       // 色
     highlight: "lightgreen",  // マウスが載った際の色
     label: "完了"        // ラベル
    },
    {
     value: in_progress,
     color: "lemonchiffon",
     highlight: "yellow",
     label: "対応中"
    },
    {
     value: not_yet,
     color: "lightpink",
     highlight: "red",
     label: "未対応"
    }
  ];
   // ↓グラフを描画するための記述
   $(document).on('turbolinks:load', function() { 
     var ctx=document.getElementById("graph-area").getContext("2d");
     window.myPie=new Chart(ctx).Pie(pieData);
    });
   
</script>

app/views/posts/new.html.erb
<div class="home-wrapper-for-add">
  <div class="container">
    <div class="row new-margin-lr0">
      <div class="new_form col-md-12">
        <div class="background row">
          <h4 class="work_title_info title_of_work-add">業務を追加する</h4>
        </div>
        
          <%= form_for @post do |f| %>
          　<div class="row">
            　<div class="col-md-12 form-group title-of-work">
            　   <div class="label-for-work_hour">
              　   <%= f.label :title,"◆タイトル(必須 ※50字以内）" %>
                </div>
              　<%= f.text_field :title,class:"form-control"%>
            　</div>
          　</div>
          
          　<div class="row">
            　<div class="col-md-12 form-group work-description">
            　   <div class="label-for-work_description">
              　   <%= f.label :description,"◆業務詳細(必須)" %>
                </div>
              　<%= f.text_area :description, size:"20vw x 10vh",class:"form-control"%>
            　</div>
          　</div> 
           
            <div class="row">
              <div class="col-md-2 form-group">
                <%= f.label :work_hour,"◆作業想定時間" %>
                <%= f.number_field	:work_hour,class:"form-control work_hour",min:"0"%>
              </div>
              <div class="col-md-1 form-group">
                <%= f.label :work_hour,"時間",class:"time-label"%>
              </div>
              <div class="col-md-offset-3 col-md-6 form-group">
                <%= f.label :due_date,"◆提出期限(必須)" %>
                <%= f.datetime_field :due_date,class:"form-control" %> 
              </div>
            </div>
            
            <div class="row">
              <div class="col-md-4 form-group">
                <%= f.label :priority,"◆優先度(必須）" %>
                <%= f.collection_select :priority,Code.priority_select,:id,:name,{size:"15vw x 5vh"},{class:"form-control"} %>
              </div>
              
              <div class="col-md-offset-2 col-md-6  form-group">
                <%= f.label :appointed_user_id,"◆担当者(必須）" %>
                <%= f.collection_select :appointed_user_id, User.all ,:id,:name,{include_blank:"選択してください"},{class:"form-control"}%>
                <!--<%#= f.collection_select :user_id, @user ,:id,:name,include_blank:true %>としていたが、undefined method `map' for nil:NilClass が発生するエラーが出たので、サイトを参照-->
                <!--users_controllerのdef newの部分に@user = User.allを追加。f.collection_selectの要素の配列部分に@userではなく、User.allを追加したら動いた。-->
                <!--カラム名が本来は:appointed_user_idになるはずが、:user_idとなっていた。そのため、ユーザーを選択しても指定したユーザーのhome画面に業務が追加されなかった。-->
              </div>
            </div>
            <div class="row btn-for-edit-add">
              <div class="col-md-offset-10 col-md-2 add-btn-location">
                <%= f.submit "業務を追加",class:"btn btn-block btn-add-work" %>
              </div>
            </div> 
          <% end %>
      </div>
    </div>
   </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row sign-up">
      <div class="col-md-offset-4 col-md-4 users-new">
        <h1 class="text-center text-white">Sign up</h1>
        <!--  submitボタンを押した時に、任意のページに飛ばしたい場合は、<%#= form_for @変数, url: ~_path do |f| %>とする-->
        <!--ただし、今回は上記の様に行ってしまうとログイン判定ができなかったので、sessions-controllerのログイン後のパスを変更する形で対応する-->
          <%= form_for @user,url: users_path  do |f| %>
            <div class="form-group">
              <%= f.label :name, class: 'text-white' %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :email, class: 'text-white' %>
              <%= f.text_field :email, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :password,class: "text-white" %>
              <%= f.password_field :password,class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation, class: "text-white" %>
              <%= f.password_field :password_confirmation,class: "form-control" %>
            </div>

            <%= f.submit "登録する" , class: 'btn-block btn-white' %>
          <% end %>
          <%= link_to 'ログインはこちら', login_path ,class: 'text-white' %>
          
      </div>
    </div>
  </div>
</div>